In [ ]:
import pandas as pd
messages = pd.read_csv(r'C:\GenAI\spam.csv', encoding='latin-1')
messages

In [ ]:
## data cleaning and preprocessing
## lowercase stopwaords lemmatizations dots and all

import re
import nltk
nltk.download('stopwords')

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer

In [ ]:
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))
corpus = []

for i in range(len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['v2'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in stop_words]
    review = ' '.join(review)
    corpus.append(review)


In [ ]:
corpus

In [ ]:
##create bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True)



In [ ]:
x=cv.fit_transform(corpus).toarray()
x.shape

In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
from sklearn.feature_extraction.text import CountVectorizer

# Download stopwords if not already done (run once)
nltk.download('stopwords')

# Initialize stemmer
ps = PorterStemmer()

reviews = [
    "I absolutely loved the movie! It was fantastic, thrilling, and full of surprises.",
    "The movie was terrible. It was boring and too long.",
    "Amazing acting and great story, but the movie was a bit slow in the middle.",
    "I didn't like the movie; it was dull and predictable.",
]

stop_words = set(stopwords.words('english'))
corpus = []

for i in range(len(reviews)):
    review = re.sub('[^a-zA-Z]', ' ', reviews[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in stop_words]
    review = ' '.join(review)
    corpus.append(review)

cv = CountVectorizer(max_features=12, binary=True)
X = cv.fit_transform(corpus).toarray()

print("Corpus after preprocessing:")
print(corpus)
print("\nFeature names (vocabulary):")
print(cv.get_feature_names_out())
print("\nBag of Words matrix shape:", X.shape)
print("\nBag of Words matrix (binary):")
print(X)

cv.vocabulary_
sorted_vocab = dict(sorted(cv.vocabulary_.items(), key=lambda x: x[0], reverse=True))
sorted_vocab


Corpus after preprocessing:
['absolut love movi fantast thrill full surpris', 'movi terribl bore long', 'amaz act great stori movi bit slow middl', 'like movi dull predict']

Feature names (vocabulary):
['absolut' 'full' 'great' 'like' 'long' 'love' 'middl' 'movi' 'predict'
 'slow' 'stori' 'surpris']

Bag of Words matrix shape: (4, 12)

Bag of Words matrix (binary):
[[1 1 0 0 0 1 0 1 0 0 0 1]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 1 1 0 1 1 0]
 [0 0 0 1 0 0 0 1 1 0 0 0]]


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\yasha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


{'surpris': 11,
 'stori': 10,
 'slow': 9,
 'predict': 8,
 'movi': 7,
 'middl': 6,
 'love': 5,
 'long': 4,
 'like': 3,
 'great': 2,
 'full': 1,
 'absolut': 0}

In [ ]:
import numpy as np

# Sum the binary presence across all documents to get word frequencies
word_freq = X.sum(axis=0)  # sums column-wise counts

# Get the feature (word) names
feature_names = cv.get_feature_names_out()

# Get indices of top 5 words by frequency (descending order)
top5_indices = np.argsort(word_freq)[::-1][:5]

print("Top 5 words across all reviews and their frequencies:")
for idx in top5_indices:
    print(f"{feature_names[idx]}: {word_freq[idx]}")


In [ ]:
 ## N-GRAM

In [25]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
from sklearn.feature_extraction.text import CountVectorizer

# Download stopwords if not already done (run once)
nltk.download('stopwords')

# Initialize stemmer
ps = PorterStemmer()

reviews = [
   "The Food is Good",
   "The Food is Not negative Good"
]

stop_words = set(stopwords.words('english'))
corpus = []

for i in range(len(reviews)):
    review = re.sub('[^a-zA-Z]', ' ', reviews[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in stop_words]
    review = ' '.join(review)
    corpus.append(review)

cv = CountVectorizer(max_features=100, binary=True,ngram_range=(3,3))
X = cv.fit_transform(corpus).toarray()

print("Corpus after preprocessing:")
print(corpus)
print("\nFeature names (vocabulary):")
print(cv.get_feature_names_out())
print("\nBag of Words matrix shape:", X.shape)
print("\nBag of Words matrix (binary):")
print(X)

cv.vocabulary_
# sorted_vocab = dict(sorted(cv.vocabulary_.items(), key=lambda x: x[0], reverse=True))
# sorted_vocab


Corpus after preprocessing:
['food good', 'food neg good']

Feature names (vocabulary):
['food neg good']

Bag of Words matrix shape: (2, 1)

Bag of Words matrix (binary):
[[0]
 [1]]


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\yasha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


{'food neg good': 0}